
language: python
sudo: true
python:
    - "3.8"

services:
    - docker

before_script: pip install docker-compose

script:
    - echo "Hello there"

deploy:
    provider: script
    script: bash scripts/deploy.sh
    on:
        branch: main
