
language: python
sudo: true
python:
    - "3.8"

services:
    - docker

before_script: pip install docker-compose

script:
    - docker-compose run app sh -c "pytest test.py -p no:cacheprovider"

after_success:
    - coveralls

deploy:
    provider: script
    skip-cleanup: true
    script: bash ci/travis-deploy.sh
    on:
        branch: main
